---
- name: Prepare
  hosts: all
  gather_facts: false
  
  tasks:
    - name: Update apt
      raw:  apt-get update

    - name: Install python .... raw
      raw: apt-get -y install python3 

    - name: Install sshd
      apt:
        name: openssh-server
        state: latest
